package com.example.alfalah.ui.theme
import androidx.compose.ui.graphics.Color
val PrimaryLight = Color(0xFF1B5E20)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFE8F5E9)
val OnPrimaryContainerLight = Color(0xFF002204)
val SecondaryLight = Color(0xFFF57F17)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFF9C4)
val OnSecondaryContainerLight = Color(0xFF4B3900)
val BackgroundLight = Color(0xFFF8FAF7)
val OnBackgroundLight = Color(0xFF191C1A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF191C1A)
val SurfaceVariantLight = Color(0xFFDFE4DC)
val OnSurfaceVariantLight = Color(0xFF434842)
val OutlineLight = Color(0xFF737971)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
